### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by nehal076** [felixgomez/gitlab-skyline#1]
![image](https://user-images.githubusercontent.com/32421196/108819940-81297000-75e1-11eb-9cfe-cfe70a01d35e.png)

Error:

```
Traceback (most recent call last):
  File "gitlab-skyline", line 190, in <module>
    main()
  File "gitlab-skyline", line 186, in main
    generate_skyline_stl(username, year, contribution_matrix)
  File "gitlab-skyline", line 57, in generate_skyline_stl
    year_contribution_list, max_contributions_by_day = parse_contribution_matrix(contribution_matrix)
  File "gitlab-skyline", line 45, in parse_contribution_matrix
    np_contribution_matrix.view('i8,i8,i8').sort(order=['f0'], axis=0)
ValueError: When changing to a larger dtype, its size must be a divisor of the total size in bytes of the last axis of the array.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DB9823B670>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by felixgomez** [comment]
I will review it as soon as I have time. Thanks for reporting the bug!

**Comment by nehal076** [comment]
Great!! It works now. 
But it only checks contributions to public repos?
