### ISSUE TITLE
Error: coroutine 'get_contributions' was never awaited

### ISSUE THREAD

**Issue by manuschillerdev** [felixgomez/gitlab-skyline#15]
When I try to create a skyline from a privat gitlab instance using docker, I get an error about `coroutine 'get_contributions' was never awaited`

```
docker run -v $PWD:/data gitlab-skyline --token ***[redacted]*** --domain ***[redacted]*** manuel.schiller 2022
/app/gitlab-skyline:186: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Fetching contributions from Gitlab...
Traceback (most recent call last):
  File "/app/gitlab-skyline", line 198, in <module>
    main()
  File "/app/gitlab-skyline", line 187, in main
    loop.run_until_complete(
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'get_contributions' was never awaited
```

**Comment by duchengyao** [comment]
the same issue

**Comment by duchengyao** [comment]
downgrade python to <=3.10

**Comment by Ganordorf** [comment]
I made a fork and this should be fixed there: https://github.com/Ganordorf/gitlab-skyline#
